### ISSUE TITLE
Running Pylon-ROS node with admin privileges

### ISSUE THREAD

**Issue by sandman** [basler/pylon-ros-camera#100]
Hi, 
is there a way to run the Pylon-ROS node with admin privileges? I tried chmod on the executable but this does not seem to be working. 

~S

**Comment by FrancoisPicardDTI** [comment]
Hello @sandman 
I assume here that you have root privileges on your machine ?
One way to solve your problem may be to modify the `launch-prefix` option in the launch file.
Instead of the following...
`<node name="$(arg node_name)" pkg="pylon_camera" type="pylon_camera_node" output="screen" respawn="$(arg respawn)" launch-prefix="$(arg launch_prefix)">
`... you can try:
`<node name="$(arg node_name)" pkg="pylon_camera" type="pylon_camera_node" output="screen" respawn="$(arg respawn)" launch-prefix="sudo">`
[Source](https://answers.ros.org/question/165246/launch-node-with-root-permissions/)
Let me know if it has solved your problem.
Best,
Francois
