### ISSUE TITLE
Pylon throwing access voilation error

### ISSUE THREAD

**Issue by blackHorz** [basler/pylon-ros-camera#130]
Hi There,

Here is my code snippet for grabbing an Image.

        `bool getCurrentFrame(cv::Mat& image)
	{
		try
		{`

			`if (isActive)
			{
				return false;
			}
			Pylon::PylonInitialize();
			CInstantCamera source = CInstantCamera(CTlFactory::GetInstance().CreateFirstDevice());
			source.Open();
			GenApi::INodeMap& nodemap = source.GetNodeMap();
			try {
				CIntegerParameter(nodemap, "GainRaw").SetValue(3);
				CIntegerParameter(nodemap, "ExposureTimeRaw").SetValue(300000);
				CIntegerParameter width(nodemap, "Width");
				CIntegerParameter height(nodemap, "Height");
				width.SetToMaximum();
				height.SetToMaximum();
			}
			catch (const GenericException& e) {
				logText(e.GetDescription());
			}

			CEnumParameter(nodemap, "AcquisitionStatusSelector").SetValue("FrameTriggerWait");
			bool isWaitingForFrameStart = CBooleanParameter(nodemap, "AcquisitionStatus").GetValue();
			if (isWaitingForFrameStart) {
				CEnumParameter(nodemap, "TriggerSelector").SetValue("FrameStart");
				CEnumParameter(nodemap, "TriggerMode").SetValue("On");
				CEnumParameter(nodemap, "TriggerSource").SetValue("Line1");
				CEnumParameter(nodemap, "TriggerActivation").SetValue("RisingEdge");
			}

			logText("Configuring souce device " + source.GetDeviceInfo().GetModelName());
			stopRequested = false;
			isActive = true;

			source.StartGrabbing(GrabStrategy_LatestImageOnly);
			CImageFormatConverter formatConvertor;
			formatConvertor.OutputPixelFormat = PixelType_BGR8packed;
			CGrabResultPtr ptrGrabResult;
			CPylonImage pylonImage;
			if (source.IsGrabbing())
			{
				source.RetrieveResult(5000, ptrGrabResult, TimeoutHandling_ThrowException);
				if (ptrGrabResult->GrabSucceeded())
				{
					formatConvertor.Convert(pylonImage, ptrGrabResult);
					cv::Mat openCvImage = cv::Mat(ptrGrabResult->GetHeight(),
						ptrGrabResult->GetWidth(), CV_8UC3, (uint8_t*)pylonImage.GetBuffer());
					image = openCvImage.clone();
					
					source.StopGrabbing();
				}
				else
				{
					logText(ptrGrabResult->GetErrorDescription(), true);
				}
			}

			if (!isActive)
			{
				return false;
			}
			try {
				logText("Requested to stop capturing.", false);
				stopRequested = true;
				ptrGrabResult.Release();
				source.Close();
				Pylon::PylonTerminate();
				isActive = false;
				logText("Capturing stopped.", false);
			}
			catch (const GenericException& e)
			{
				logText("Capture thread exception:", true);
				logText(e.GetDescription(), true);
			}
		}
		catch (const GenericException& e)
		{
			logText("Capture thread exception:", true);
			logText(e.GetDescription(), true);
		}

		return true;
	}`

It runs fine until last try and catch block where i want to release the objects. I can also not capture the exception, so not sure where exactly it is happening.

Error
Exception thrown at 0x00007FFF88D7041C (PylonBase_v7_1.dll) in PedWelder.exe: 0xC0000005: Access violation reading location 0x000001A1E96D9CC8.

**Comment by FrancoisPicardDTI** [comment]
Hello @blackHorz 
This issue is not related to the ros/ros2 driver as far as I am understanding your code, so I am going to close it.
Now that it is said, here are a couple of suggestions:
- Add some logText calls before each code line in your last try to determine which one is generated this exception. Or something like `cerr << "My message" << e.GetDescription() << endl;`
- Looking at your code quickly, `ptrGrabResult.Release(); should be ptrGrabResult->Release();`. As it is a smart pointer, you don't need this line in my opinion.
- Look closely at Pylon API documentation, [from here for instance](https://docs.baslerweb.com/pylonapi/cpp/pylon_programmingguide#grabbing-images-in-a-loop), and try to implement the grabbing loop accordingly.

Hoping these suggestions will help you moving forward.
