### ISSUE TITLE
Feature Request: Auto Exposure and both Auto Function ROI's

### ISSUE THREAD

**Issue by MattsProjects** [basler/pylon-ros-camera#33]
Hi there,
In case someone would like to add some features, someone has brought to me an application needing the Auto Exposure and Auto Function ROI's (both for Brightness and White Balance). Unfortunately at the moment I don't have the resources to implement these myself. I'm not sure of the urgency, just that they would be needed at some point. (I also file the issue so that I won't forget one day when I am able to work on them :)).
Thanks and I hope everyone is healthy and doing well during these strange days!!
-Matt

**Comment by pablo-quilez** [comment]
Hi Matt,
Thanks to you and also we hope you are healthy and doing well during these days! I will close the issue because we need more details to know exactly your request. Auto Exposure is already implemented, and Auto ROI would be application-dependent, if I understand correctly. This means that probably it would be not a generic solution but a concrete solution for your case.
Cheers,
Pablo
