### ISSUE TITLE
no device found, will try once more in 2 s

### ISSUE THREAD

**Issue by AkmaralMoldagalieva** [basler/pylon-ros-camera#48]
Hello !
Thanks for this great job and making it available to everyone. 

I am using an Ethernet camera (GigE) and failing to get it connected. With lfconfig I can see the IP address of my camera, it is connected, but pylon_camera_ip_configuration.launch can't establish a connection with my camera returning 'no device found, will try once more in 2 s' . Consequently I am getting warning ' No camera present '. Any hints or suggestions ?

**Comment by m-binev** [comment]
@AkmaralMoldagalieva Hi, have you checked if trivial things like IP addresses and Subnet Masks are matching? Just an example: for Class C addresses:
NIC: 192.168.0.2, subnet: 255.255.255.0
camera: 192.168.0.10, subnet: 255.255.255.0

for Auto IP (not more than one NIC in the system):
NIC: 169.254.0.2, subnet: 255.255.0.0
camera: 169.254.0.10, subnet: 255.255.0.0

Use the pylon IP Configurator to configure the camera accordingly. 
For configuring the NIC use ifconfig. 
Of course, if you have issues with the firewall, you have to switch it off.

**Comment by AkmaralMoldagalieva** [comment]
@m-binev Hello !
 
Thank you for your response and guidance.

What do you mean by using pylon IP Configurator to configure the camera  **accordingly** ? Is there anything to be taken into account depending on whether it is Class C or Auto IP ? 

I set up IP address of the camera and NIC manually (they share the same subnet, 192.168.0.XXX) .  Firewall is inactive - checked. But still failure to see my camera.

**Comment by m-binev** [comment]
@AkmaralMoldagalieva Hi, ROS is just a middleware on top of the pylon API. See here:
https://www.baslerweb.com/fp-1591878203/media/downloads/documents/application_notes/AW00149103000_Interfacing_Basler_Cameras_with_ROS~1.pdf 
That is, pylon with all its GUI tools is a prerequisite for running ROS. In case of GigE, you usually have to use the pylon Ip Configurator tool (either start it from pylon Viewer > Tools, or from the location where it was installed) to change the IP address of a GigE camera -especially if it should use other but Auto IP. 
Please have a look at the pylon README > Troubleshooting to find out more on that:
https://www.baslerweb.com/fp-1594648601/media/downloads/software/pylon_software/README~2.txt 

>they share the same subnet, 192.168.0.XXX
What are the subnets of both? Please try to provide more detailed information, because it is otherwise hard to help you efficiently))

**Comment by AkmaralMoldagalieva** [comment]
OK, thank you very much ! It should work, everything is well explained in the documentary you provided.

**Comment by AkmaralMoldagalieva** [comment]
Can it be the reason that I am using Teledyne DALSA GigE not Basler ?

**Comment by m-binev** [comment]
@AkmaralMoldagalieva Hi, you are kidding/killing me)) This is a Basler pylon ROS adapter, which is meant for Basler cameras only. Thus, any 3rd party cameras are not supported, of course... Cheers.
