### ISSUE TITLE
Influence parameter of frame rate

### ISSUE THREAD

**Issue by hannespimmel** [basler/pylon-ros-camera#68]
Hello together,

How does the trigger timeout and the grabbing timeout influence the frame rate/image acquisition, when i run my camera in the free run mode with the grabbing strategy latest image only?

I wolud appreciate any explanation of the realtion of these two parameters in the config-file. Because i want to understand the whole process behind the free run mode and the parameters

Thanks for any help!

**Comment by m-binev** [comment]
@hannespimmel Hi, the following question is actually a little misleading:
"How does the trigger timeout and the grabbing timeout influence the frame rate/image acquisition, when i run my camera in the free run mode with the grabbing strategy latest image only?"
That is, when you run a camera in a free-run mode, there is no trigger timeout related to the image acquistion, because the camera triggers itself automatically. 
The trigger timeout is rather related to triggering the camera by software (or hardware) trigger. Pay attention, the default configuration is software trigger, which definitely limits the maximum possible frame rate of a camera.
The grabbing timeout defines how long the driver will be waiting for an image to be received. In pylon, the default timeout value is 3000ms, which is obviously enough for 99% of the use cases - unless you trigger a camera every > 3 seconds. Ohterwiese, this timeout has no influence on the frame rate. 
The grabbing strategy "Latest image only" defines how the pylon camera class (e.g., BaslerGigEInstantCamera) will handle image buffers in the input queue. That is, in this case the camera class will make sure to keep only the latest image in the queue to be picked up by the application. Whenever a new image is grabbed, the other image in the queue will be released and reused for grabbing. Obvuosly, this also has nothing to do with the acquisition frame rate of the camera - unless you pick up buffers and do not release them on time - in this case the buffer queue could run empty, which may result in losing image data. But the acquisition frame rate of the camera is actually not influenced.
I hope that helps. Regards.
