### ISSUE TITLE
2 basler cameras synchronizes over USB

### ISSUE THREAD

**Issue by albeit07** [basler/pylon-ros-camera#99]
Hi guys, I am currently trying to synchronize 2 a2A1920-160ucPRO cameras via the software trigger. Via rosservicelist I have changed the following parameters for this.

rosservice call /ace_RGB_Right/pylon_camera_node/set_trigger_activation "value: 0"
rosservice call /ace_RGB_Left/pylon_camera_node/set_trigger_activation "value: 0"

rosservice call /ace_RGB_Right/pylon_camera_node/set_trigger_selector "value: 0"
rosservice call /ace_RGB_Left/pylon_camera_node/set_trigger_selector "value: 0"

rosservice call /ace_RGB_Right/pylon_camera_node/set_trigger_mode "data: true"
rosservice call /ace_RGB_Left/pylon_camera_node/set_trigger_mode "data: true"

rosservice call /ace_RGB_Right/pylon_camera_node/set_trigger_source "value: 0"
rosservice call /ace_RGB_Left/pylon_camera_node/set_trigger_source "value: 0"

But if I call the, the function:

ts=message_filters.ApproximateTimeSynchronizer([im1, im2], 2, 0.001)

So with a maximum difference of time stamps of one millisecond, the function is not called often. Example. The yaml file is set to 4 hearts. But I only get images every 3-4 seconds, which is always very underestimated.
Have I set the parameters for the software trigger that were mentioned above wrong?

**Comment by amarnathreddy0201** [comment]
Hi Sir/Mam,
I tried to synchronizes the Basler USB Cameras. there is no proper information about to synchronizing of two cameras.

I Studied lot of documents for the syn of two cameras. Every documentation saying using GigE cameras it's possible.

If you done synchronizing of 2 USB Basler cameras suggest me to do that.

Thanks,
ANR S

**Comment by m-binev** [comment]
@albeit07 @amarnathreddy0201 Hi, the topic synchronisation of miltiple cameras is not so trivial, because 1) the different camera interfaces & protocols (GigE, USB) are different (and behave different), and 2) the use cases and requirements for synchronisation could vary. 
To 1) yes, the GigE protocol allows better and easier sync of multiple cameras(action commands, scheduled action commands, PTP (sync free run), however the USB protocol simply does not support similar features. Now, in all cases you can still Software Trigger to trigger the (serial) image acquisition of multiple cameras, while this would cause a delay ot 3-4 ms. You can also use Hardware Trigger to simultaneuosly trigger multiple cameras, or you can also connect the IO (output) lines of one camera to the (input) IO lines of other cameras. So, there are multiple options to do so.
To 2) when speaking of sync of cameras, from Machine Vision perspective (Factory automation, etc.) we typically consider the point when cameras are being triggerred, not when the images are received. If you expect to get images of multiple cameras syncronously - well, there are a lot of aspects to be considered... On ROS you have the general fact of images being additionally copied before being published. Depending of the image size, on system ressources, etc. this could cause some delays - even of a few seconds. 
I hope that sheds some more lights into the darkness))
Cheers,

**Comment by farhad-dalirani** [comment]
How can I hardware trigger two Basler USB-3 cameras? I have the cable that connects both cameras to each other.

**Comment by FrancoisPicardDTI** [comment]
Hello @albeit07 
I suppose you managed to solve your problem? Maybe you can share here how you did it?

**Comment by FrancoisPicardDTI** [comment]
I am closing this issue for now as it does not seem to be active anymore.
